### ISSUE TITLE
StableLayout

### ISSUE THREAD

**Issue by Lokathor** [rust-secure-code/mem-markers#4]
Opt-in trait for types that have a defined layout.

Either a primitive layout, or repr(C), or repr(Rust) with layout fixed for some reason (usually because the type is declared stable compared to another type, eg: NonNull).

This could usually be derived safely and maybe we'd also have to have a way to unsafe impl it for some particular library types.

**Comment by rylev** [comment]
This is now in master. It's not feature complete but we should create issues for the various features that are missing.
